level->push_back(Point(8, 34)); // A
level->push_back(Point(8, 42)); // B
level->push_back(Point(9, 34)); // C
level->push_back(Point(9, 41)); // D
level->push_back(Point(10, 42)); // E
level->push_back(Point(13, 40)); // F
level->push_back(Point(14, 41)); // G
level->push_back(Point(15, 41)); // H
level->push_back(Point(16, 40)); // I
level->push_back(Point(16, 42)); // J
