level->push_back(Point(8, 37)); // A
level->push_back(Point(8, 38)); // B
level->push_back(Point(8, 43)); // C
level->push_back(Point(9, 38)); // D
level->push_back(Point(9, 39)); // E
level->push_back(Point(9, 42)); // F
level->push_back(Point(9, 44)); // G
level->push_back(Point(11, 41)); // H
level->push_back(Point(14, 39)); // I
level->push_back(Point(14, 40)); // J
level->push_back(Point(14, 41)); // K
level->push_back(Point(14, 42)); // L
