level->push_back(Point(8, 27)); // A
level->push_back(Point(8, 28)); // B
level->push_back(Point(8, 30)); // C
level->push_back(Point(8, 31)); // D
level->push_back(Point(9, 30)); // E
level->push_back(Point(12, 27)); // F
level->push_back(Point(13, 26)); // G
level->push_back(Point(13, 27)); // H
level->push_back(Point(13, 30)); // I
level->push_back(Point(13, 32)); // J
level->push_back(Point(13, 34)); // K
level->push_back(Point(14, 27)); // L
level->push_back(Point(14, 33)); // M
level->push_back(Point(15, 26)); // N
level->push_back(Point(15, 27)); // O
level->push_back(Point(15, 28)); // P
level->push_back(Point(15, 30)); // Q
level->push_back(Point(15, 33)); // R
level->push_back(Point(16, 32)); // S
level->push_back(Point(16, 34)); // T
