level->push_back(Point(8, 32)); // A
level->push_back(Point(8, 33)); // B
level->push_back(Point(8, 37)); // C
level->push_back(Point(8, 38)); // D
level->push_back(Point(9, 35)); // E
level->push_back(Point(9, 37)); // F
level->push_back(Point(9, 40)); // G
level->push_back(Point(9, 41)); // H
level->push_back(Point(12, 36)); // I
level->push_back(Point(13, 32)); // J
level->push_back(Point(13, 35)); // K
level->push_back(Point(14, 32)); // L
level->push_back(Point(15, 33)); // M
