level->push_back(Point(8, 34)); // A
level->push_back(Point(9, 34)); // B
level->push_back(Point(9, 35)); // C
level->push_back(Point(9, 37)); // D
level->push_back(Point(9, 38)); // E
level->push_back(Point(10, 32)); // F
level->push_back(Point(10, 33)); // G
level->push_back(Point(11, 35)); // H
level->push_back(Point(12, 36)); // I
level->push_back(Point(12, 39)); // J
level->push_back(Point(13, 33)); // K
level->push_back(Point(13, 34)); // L
level->push_back(Point(13, 37)); // M
level->push_back(Point(15, 36)); // N
level->push_back(Point(16, 35)); // O
level->push_back(Point(17, 35)); // P
