level->push_back(Point(9, 29)); // A
level->push_back(Point(9, 31)); // B
level->push_back(Point(9, 33)); // C
level->push_back(Point(9, 35)); // D
level->push_back(Point(9, 37)); // E
level->push_back(Point(11, 30)); // F
level->push_back(Point(11, 32)); // G
level->push_back(Point(11, 35)); // H
level->push_back(Point(11, 37)); // I
level->push_back(Point(12, 30)); // J
level->push_back(Point(14, 30)); // K
level->push_back(Point(14, 32)); // L
level->push_back(Point(14, 34)); // M
level->push_back(Point(15, 33)); // N
level->push_back(Point(16, 29)); // O
level->push_back(Point(16, 31)); // P
level->push_back(Point(16, 35)); // Q
level->push_back(Point(18, 29)); // R
