CXX = g++
RM = rm -f
CXXFLAGS = -O0 -Wall -Wextra -g3 -gdwarf-2
OBJECTS = Amulet.o Armor.o Axe.o Boomerang.o Boots.o Bow.o BroadSword.o Cloak.o Club.o Corpse.o Crossbow.o Dagger.o Dart.o Flail.o Food.o Gloves.o Hammer.o Helmet.o Item.o Javelin.o Knife.o Lance.o LongSword.o Mace.o Monster.o MorningStar.o PickAxe.o Polearm.o Quarterstaff.o Saber.o Scimitar.o Shield.o Shirt.o ShortSword.o Shuriken.o Sling.o Spear.o Suit.o Trident.o TwoHandedSword.o UnicornHorn.o Weapon.o Whip.o

analyzers: $(OBJECTS)

Amulet.o: Amulet.h Amulet.cpp
Armor.o: Armor.h Armor.cpp
Axe.o: Axe.h Axe.cpp
Boomerang.o: Boomerang.h Boomerang.cpp
Boots.o: Boots.h Boots.cpp
Bow.o: Bow.h Bow.cpp
BroadSword.o: BroadSword.h BroadSword.cpp
Cloak.o: Cloak.h Cloak.cpp
Club.o: Club.h Club.cpp
Corpse.o: Corpse.h Corpse.cpp
Crossbow.o: Crossbow.h Crossbow.cpp
Dagger.o: Dagger.h Dagger.cpp
Dart.o: Dart.h Dart.cpp
Food.o: Food.h Food.cpp
Flail.o: Flail.h Flail.cpp
Gloves.o: Gloves.h Gloves.cpp
Hammer.o: Hammer.h Hammer.cpp
Helmet.o: Helmet.h Helmet.cpp
Item.o: Item.h Item.cpp
Javelin.o: Javelin.h Javelin.cpp
Knife.o: Knife.h Knife.cpp
Lance.o: Lance.h Lance.cpp
LongSword.o: LongSword.h LongSword.cpp
Mace.o: Mace.h Mace.cpp
Monster.o: Monster.h Monster.cpp
MorningStar.o: MorningStar.h MorningStar.cpp
PickAxe.o: PickAxe.h PickAxe.cpp
Polearm.o: Polearm.h Polearm.cpp
Quarterstaff.o: Quarterstaff.h Quarterstaff.cpp
Saber.o: Saber.h Saber.cpp
Scimitar.o: Scimitar.h Scimitar.cpp
Shield.o: Shield.h Shield.cpp
Shirt.o: Shirt.h Shirt.cpp
ShortSword.o: ShortSword.h ShortSword.cpp
Shuriken.o: Shuriken.h Shuriken.cpp
Sling.o: Sling.h Sling.cpp
Spear.o: Spear.h Spear.cpp
Suit.o: Suit.h Suit.cpp
Trident.o: Trident.h Trident.cpp
TwoHandedSword.o: TwoHandedSword.h TwoHandedSword.cpp
UnicornHorn.o: UnicornHorn.h UnicornHorn.cpp
Weapon.o: Weapon.h Weapon.cpp
Whip.o: Whip.h Whip.cpp

.PHONY: clean
clean:
	$(RM) *.o *.gch
