#!/bin/sh
# Runs saiph in a loop while avoiding overwriting stuff.

LOGS=logs
OPT=-l
KILL="killall -q nethack"

if [ x"$1" = x-t ]; then
	KILL=":"
	OPT=-t
	LOGS=tlogs
fi

make || exit $?
mkdir -p $LOGS

while :; do
    sleep 1 # no thrashing
    $KILL # nethack likes to use 100% cpu if saiph crashes
    TIME=$(date +%Y%m%d%H%M%S)
    ./saiph $OPT -L $LOGS/$TIME.log -T $LOGS/$TIME.ttyrec
done
